platform :ios, '9.0'

target 'walk:now' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for walk:now
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  target 'walk:nowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'walk:nowUITests' do
    # Pods for testing
  end
  

end
